name: Build and Deploy to Firebase Hosting
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install Dependencies
        run: npm install

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Build
        run: ng build --configuration production --optimization

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Firebase Login
        run: firebase login --no-localhost --token "${{ secrets.FIREBASE_TOKEN }}"

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting
